feature/debug_docker
Apply codestyle to fix code style errors in githook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -17,9 +17,20 @@ then
     echo "\nThere are no code-style errors, the commit can proceed.\n"
 else
     echo "\n###########################################################################\n"
-    echo "There are code-style errors, run make code-style-verbose to see the errors.\n"
-    echo "###########################################################################\n"
-    exit 1
+    echo "\n There are code-style errors, trying to fix them.\n"
+    docker run -v $(pdw)/../app/:/tmp/code webpp/codestyle -i /tmp/code -x '/tmp/code/docs' '/tmp/code/migrations'
+    if [ $? -lt 1 ]
+        then
+            echo "\n##############################################################\n"
+            echo "Codestyle errors fixed.\n"
+            echo "##############################################################\n"
+        else
+            echo "\n###########################################################################\n"
+            echo "There are unfixables code-style errors, run make code-style-verbose to see the errors.\n"
+            echo "###########################################################################\n"
+            exit 1
+            
+    fi
 fi
 
 echo "Generating documentation before push.\n"
